# Configuración de Nginx para balanceo de carga

events {
    worker_connections 1024;
}

http {
    # Define el grupo de servidores para el microservicio de recepción de alertas
    upstream ms_recepcion_alertas_cluster {
        # least_conn: Envía la petición al servidor con el menor número de conexiones activas
        least_conn;
        server ms-recepcion-alertas-1:3001;
        server ms-recepcion-alertas-2:3001;
        server ms-recepcion-alertas-3:3001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ms_recepcion_alertas_cluster;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}